### ISSUE TITLE
Error running vcf2xg.sh

### ISSUE THREAD

**Issue by mariarecuerda6** [MoMI-G/MoMI-G#117]
Hello,

I want to generate the pcf file but I get the following error when running the vcf2xg.sh in my own data. The vcf file was generated using minigraph-cactus pangenome pipeline. 

./vcf2gfa/vcf2pcf.rb:24:in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from ./vcf2gfa/vcf2pcf.rb:24:in `block in <main>'
        from ./vcf2gfa/vcf2pcf.rb:18:in `each'
        from ./vcf2gfa/vcf2pcf.rb:18:in `<main>'
+ input=.//sporophila_output.pcf
+ reference=/workdir/mjr432/IBEB009696_masked.1.fa
+ pref=.//sporophila_output.pcf
+ sort -t, -k 7n .//sporophila_output.pcf
+ awk -F '[,:]' '{print $1,"\t",$2,"\n",$4,"\t",$5}' /dev/fd/63
+ sed -e 's/[ ]*//g'
++ sed 1d .//sporophila_output.pcf
+ sort -k 1,1 -k 2,2n
+ uniq
+ '[' '!' -s /workdir/mjr432/IBEB009696_masked.1.fa.fai ']'
++ dirname ./vcf2gfa/pcf2gfa.sh
+ ruby ./vcf2gfa/json_to_breakpoint_list.rb .//sporophila_output.pcf.bp.tsv /workdir/mjr432/IBEB009696_masked.1.fa
+ cat .//sporophila_output.pcf.bp.tsv breakpoint_list_tmp.tsv
+ sort -k 1,1 -k 2,2n
+ uniq
+ awk '{print $1 "\t" $2 "\t" $2}' .//sporophila_output.pcf.bp.merged.tsv
+ awk '{print $1 "\t0\t" $2}' /workdir/mjr432/IBEB009696_masked.1.fa.fai
+ bedtools intersect -a .//sporophila_output.pcf.bp.merged.bed -b .//sporophila_output.pcf.reference.tsv
+ cut -f 1,2
++ dirname ./vcf2gfa/pcf2gfa.sh
+ ruby ./vcf2gfa/gfa_generator.rb .//sporophila_output.pcf.bp.merged.filtered.tsv .//sporophila_output.pcf.output.pcf /workdir/mjr432/IBEB009696_masked.1.fa
[faidx] Zero length sequence: chr1:0-49999
[faidx] Zero length sequence: chr10:0-49999
[faidx] Zero length sequence: chr100:0-49999
[faidx] Zero length sequence: chr101:0-49999
[..........]
error [vg convert]: Input GFA is not acceptable.
GFA format error: On pass 1: On line 2: At column 5: Expected nonempty value while parsing sequence
error[VPKG::load_one]: Correct input type not found in .//sporophila_output.vg.old while loading handlegraph::MutablePathDeletableHandleGraph
error[VPKG::load_one]: Correct input type not found while loading handlegraph::HandleGraph

I check the gfa that is generated and it just have to columns in line 2, but I have already the xg and the gfa files that were generated at the same time as the vcf file that look fine, it is possible to run it with my own gfa? 

Thank you in advance for your assistance.

**Comment by asunboi** [comment]
Hi, I'm having the exact same issue. Was wondering if you or the developers have found any solution to this?

**Comment by mariarecuerda6** [comment]
I haven't find any solution..

**Comment by cristinasanchezf** [comment]
Hi! I'm trying to run the app and I got a similar error. 

In my case part of the issue was fixed by changing this line: `awk '{print $1 "\t0\t" $2}' $reference.fai > $pref.reference.tsv`, to `awk '{print $1 "\t1\t" $2}' $reference.fai > $pref.reference.tsv`. This command is at the 35th line of script `scripts/vcf2gfa/pcf2gfa.sh`. I guess 

However, I'm still getting similar errors but the pipeline can run some additional steps. 

I tried to execute the app with a VCF file generated by older versions of Sniffles (v1.0.12), but it didn’t work either.
