### ISSUE TITLE
error running vcf2xg on singularity

### ISSUE THREAD

**Issue by olechnwin** [MoMI-G/MoMI-G#57]
Hi,

I am trying to run `vcf2xg` using singularity and got an error. I tried several different ways but have the same errors:
```
$ singularity -s run docker://momigteam/momig-tools:latest ~/Data/A673_pacbio/HiFi/vcf/A673.HiFi.hg19.var.vcf test_output ~/opt/vg ~/hg19/hg19.fa
/usr/src/app/vcf2gfa/vcf2pcf.rb:89:in `+': no implicit conversion of nil into String (TypeError)
        from /usr/src/app/vcf2gfa/vcf2pcf.rb:89:in `block in <main>'
        from /usr/src/app/vcf2gfa/vcf2pcf.rb:10:in `each'
        from /usr/src/app/vcf2gfa/vcf2pcf.rb:10:in `<main>'
```
```
$ singularity -s run docker://momigteam/momig-tools:latest ~/Data/A673_pacbio/HiFi/vcf/A673.HiFi.hg19.var.vcf test_output ~/opt/vg hg19
/usr/src/app/vcf2gfa/vcf2pcf.rb:89:in `+': no implicit conversion of nil into String (TypeError)
        from /usr/src/app/vcf2gfa/vcf2pcf.rb:89:in `block in <main>'
        from /usr/src/app/vcf2gfa/vcf2pcf.rb:10:in `each'
        from /usr/src/app/vcf2gfa/vcf2pcf.rb:10:in `<main>'
```
I downloaded binary vg to ~/opt/vg and have changed the permission. 
Can you please let me know how to fix this? Thank you!

**Comment by 6br** [comment]
Thank you for using MoMI-G.
I found that the momig-tools docker was outdated.
Is it possible to use the latest version via `docker pull momigteam/momig-tools:autobuild` or `singularity -s run docker://momigteam/momig-tools:autobuild` ?

**Comment by olechnwin** [comment]
Thank you. The latest version works!
